spring:
  application:
    name: shortly

#|| jdbc:mysql://localhost:3306/shortlydb
#  shorty
#  Shorty@123

  data:
    redis:
      url: ${REDIS_URL_INTERNAL}


  datasource:
      url: ${POSTGRES_URL}
      username: ${POSTGRES_USERNAME}
      password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate: { }

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRY}
  refresh_expiration: ${JWT_REFERESH_EXPIRY}


server:
  port: ${PORT:8080}



logging:
  level:
    org.springframework.security: DEBUG

app:
 backend:
   base:
    url: ${BACKEND_URL}